# Generated by Django 4.1.3 on 2022-11-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact', models.PositiveIntegerField()),
                ('contact_number', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField(max_length=150)),
                ('sex', models.CharField(choices=[('m', 'm'), ('f', 'f')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
