# Generated by Django 4.1.3 on 2022-11-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_centres', '0001_initial'),
        ('user', '0002_alter_user_details_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='healthcare_centres',
            field=models.ManyToManyField(to='healthcare_centres.hospitals'),
        ),
    ]
