# Generated by Django 4.1.3 on 2022-11-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_details_healthcare_centres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='healthcare_centres',
        ),
    ]
