# Generated by Django 4.1.3 on 2022-11-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_details_healthcare_centres'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingpayments',
            name='user_details',
        ),
        migrations.AddField(
            model_name='pendingpayments',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_details'),
        ),
    ]
