# Generated by Django 4.1.3 on 2022-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_details_healthcare_centres'),
        ('healthcare_centres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='user_details',
            field=models.ManyToManyField(to='user.user_details'),
        ),
    ]
