# Generated by Django 4.1.3 on 2022-11-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_details_healthcare_centres'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservitals',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_details'),
        ),
    ]
